name: database_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=3.9.0"

dependencies:
  xml: ^6.0.0
  path: ^1.8.2
  kana_kit: 2.1.1
  isar_community: 3.2.0-dev.2
  console_bars: ^1.1.0
  tuple: ^2.0.1
  async: ^2.10.0
  compute: ^1.0.2
  archive: ^4.0.1
  csv: ^6.0.0
  json_serializable: ^6.6.1
  json_annotation: ^4.9.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
  build_runner: any
  isar_community_generator:
    git:
      url: https://github.com/callumw-k/isar-community
      ref: migrating-to-source_gen-3
      path: packages/isar_community_generator/