name: database_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

isar_version: &isar_version 3.0.5

dependencies: 
  xml: ^6.0.0
  path: ^1.8.2
  kana_kit: ^2.0.0
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: any
  isar_generator: *isar_version