name: database_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

isar_version: &isar_version 4.0.3 # 3.1.0+1

dependencies:
  xml: ^6.0.0
  path: ^1.8.2
  kana_kit:
    git:
      url: https://github.com/CaptainDario/kana_kit
  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  console_bars: ^1.1.0
  tuple: ^2.0.1
  async: ^2.10.0
  compute: ^1.0.2
  archive: ^3.3.2
  csv: ^5.0.2
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: any
