name: database_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

isar_version: &isar_version 3.0.5

dependencies:
  xml: ^6.0.0
  path: ^1.8.2
  kana_kit:
    git:
      url: https://github.com/CaptainDario/kana_kit
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  console_bars: ^1.1.0
  tuple: ^2.0.1
  async: ^2.10.0
  compute: ^1.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: any
  isar_generator: *isar_version
